// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6YC7UEuFYQgz8l7hvIRQ2KoemzcK-6eg',
    appId: '1:197212542807:web:c7c1c141c8ddfb62491012',
    messagingSenderId: '197212542807',
    projectId: 'craftshubapp',
    authDomain: 'craftshubapp.firebaseapp.com',
    storageBucket: 'craftshubapp.appspot.com',
    measurementId: 'G-R7G2QW5Y5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqlZmDNxn6PQcFJXBNymYxpBcDj-HaGTE',
    appId: '1:197212542807:android:785478e88352d633491012',
    messagingSenderId: '197212542807',
    projectId: 'craftshubapp',
    storageBucket: 'craftshubapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNGDvm_Ui9zUw8u5YyTNf1sOV6NXSxDN0',
    appId: '1:197212542807:ios:abb3aec0dc051d7e491012',
    messagingSenderId: '197212542807',
    projectId: 'craftshubapp',
    storageBucket: 'craftshubapp.appspot.com',
    iosBundleId: 'com.example.craftshubapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNGDvm_Ui9zUw8u5YyTNf1sOV6NXSxDN0',
    appId: '1:197212542807:ios:abb3aec0dc051d7e491012',
    messagingSenderId: '197212542807',
    projectId: 'craftshubapp',
    storageBucket: 'craftshubapp.appspot.com',
    iosBundleId: 'com.example.craftshubapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6YC7UEuFYQgz8l7hvIRQ2KoemzcK-6eg',
    appId: '1:197212542807:web:2e509f7b8559cff4491012',
    messagingSenderId: '197212542807',
    projectId: 'craftshubapp',
    authDomain: 'craftshubapp.firebaseapp.com',
    storageBucket: 'craftshubapp.appspot.com',
    measurementId: 'G-26MK7EQ218',
  );
}
